import Head from "next/head";
import Image from "next/image";
import ProgressBar from "@ramonak/react-progress-bar";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pepe Drive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.cdnfonts.com/css/vcr-osd-mono" rel="stylesheet"></link>
      </Head>
      <main className={styles.pdrive_landing_page}>
        <div className={styles.pdrive_hero_section}>
          <div className={styles.pdrive_hero_section}>
            <div className={styles.pdrive_page_top}>
              <div className={styles.pdrive_logo_box}>
                <div className={styles.pdrive_logo_img}>
                  <div className={styles.pdrive_logo_src}>
                    <Image
                      src="/../public/images/eth-logo.png"
                      alt="Logo"
                      width={65}
                      height={105}
                    />
                  </div>
                </div>

                <a href="#" className={`${styles.cnt_walet_text} ${styles.font_style_1}`}>
                  CONNECT WALLET
                </a>
              </div>
              <div className={styles.eth_details_box}>
                <article className={`${styles.cnt_walet_dtails} ${styles.font_style_1}`}>
                  ETH:$1689 | GAS:34 GWAI
                </article>
              </div>
            </div>
            <div className={styles.pdrive_page_body}>
              <Image
                src="/../public/images/pdrive-main-logo.png"
                alt="Logo"
                width={940}
                height={260}
              />
              <div className={styles.pdrive_mint_steps}>
                <article className={` ${styles.font_style_1}`}>
                  SOON... FEW..
                </article>
              </div>
            </div>
            <div className={styles.pdrive_page_bottom}>
              <div className={styles.pdrive_page_sound}>
                <Image
                  src="/../public/images/sound-off.png"
                  alt="Logo"
                  width={80}
                  height={80}
                />
              </div>
              <div className={styles.pdrive_mint_status}>
                <article className={`${styles.mint_status_text} ${styles.font_style_1}`}>
                  X DAYS TO MINT
                </article>
                <ProgressBar completed={60} />

              </div>
              <div className={styles.pdrive_page_social}>
                <Image
                  src="/../public/images/twitter-logo.png"
                  alt="Logo"
                  width={80}
                  height={80}
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
